server:
  port: 3386
db:
  dbName: sql_demo
  dbDriver: mysql
  dbUser: root
  dbPassword: 123456
  dbHost: 127.0.0.1
  dbPort: 55001
  charset: utf8
  maxConn: 200
  maxOpen: 10
redis:
  host: 127.0.0.1
  port: 55000